In [73]:
import pandas as pd 
import numpy as np
from scipy import stats

In [74]:
df=pd.read_csv('heart.csv')
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [75]:
z_scores = np.abs(stats.zscore(df['Age']))
z_scores

print(np.mean(df['Age']))
print(np.std(df['Age']))

threshold = 3
df_no_outliers = df[(z_scores < threshold)]
df_no_outliers

53.510893246187365
9.427477516153495


Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [76]:
from sklearn.preprocessing import LabelEncoder

# Label encoding
encoder = LabelEncoder()
df['Sex'] = encoder.fit_transform(df['Sex'])

df['ChestPainType'] = encoder.fit_transform(df['ChestPainType'])
df['RestingECG'] = encoder.fit_transform(df['RestingECG'])
df['ExerciseAngina'] = encoder.fit_transform(df['ExerciseAngina'])
df['ST_Slope'] = encoder.fit_transform(df['ST_Slope'])

df

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         2             0  
1      156               0      1.0         1             1  
2       98               0      0.0         2             0  
3      108               1      1.5         1             1  
4      122               0      0.0         2             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         2             0  

[918 rows x 12 columns]

In [77]:
X = df
y = df.HeartDisease

In [78]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
X_scaled = standard_scaler.fit_transform(X)
X_scaled

array([[-1.4331398 ,  0.51595242,  0.22903206, ..., -0.83243239,
         1.05211381, -1.11311472],
       [-0.47848359, -1.93816322,  1.27505906, ...,  0.10566353,
        -0.59607813,  0.89837999],
       [-1.75135854,  0.51595242,  0.22903206, ..., -0.83243239,
         1.05211381, -1.11311472],
       ...,
       [ 0.37009972,  0.51595242, -0.81699495, ...,  0.29328271,
        -0.59607813,  0.89837999],
       [ 0.37009972, -1.93816322,  0.22903206, ..., -0.83243239,
        -0.59607813,  0.89837999],
       [-1.64528563,  0.51595242,  1.27505906, ..., -0.83243239,
         1.05211381, -1.11311472]])

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state=30)

In [80]:
#Logictic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression() 
model.fit(X_train, y_train) 

LogisticRegression()

In [81]:
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

1.0
1.0


In [82]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1])

In [83]:
#SVM
from sklearn import svm
from sklearn import metrics

clf = svm.SVC(kernel='linear') 
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [84]:
from sklearn.ensemble import RandomForestClassifier

classifier=RandomForestClassifier(n_estimators=100)

classifier.fit(X_train,y_train)

RandomForestClassifier()

In [85]:
Pred = classifier.predict(X_test)
print(Pred) 

[1 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0
 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0 1 1 0
 0 1 0 0 0 0 0 1 0 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 0 0 0
 0 0 0 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 1
 0 0 1 0 1 1 1 1 0 0 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 1 1]


In [86]:
from sklearn.metrics import classification_report
rand_score=classifier.score(X_test, y_test)
classification_report_rf=classification_report(y_test,Pred)
print("Accuracy score:",rand_score)  
print(classification_report_rf)

Accuracy score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        84
           1       1.00      1.00      1.00       100

    accuracy                           1.00       184
   macro avg       1.00      1.00      1.00       184
weighted avg       1.00      1.00      1.00       184



In [87]:
from sklearn.decomposition import PCA
pca = PCA(0.98)

X_pca = pca.fit_transform(X)
X_pca.shape

(918, 3)

In [88]:
X_pca

array([[ 92.31150296, -29.44339488, -12.02317233],
       [-17.14318296, -13.7477133 , -31.48618772],
       [ 81.9060306 ,  38.22291707,  16.06579722],
       ...,
       [-69.00452422,  17.34009145,   5.33851425],
       [ 39.20696975, -33.59377142,  -6.12340024],
       [-21.43603879, -37.22738029, -13.58459443]])

In [89]:
pca.explained_variance_ratio_

array([0.92020198, 0.04913467, 0.0250812 ])

In [90]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size = 0.2, random_state=30)

In [91]:

model = LogisticRegression()
model.fit(X_train_pca, y_train)
model.score(X_test_pca, y_test)

0.7119565217391305

In [92]:
#taking only 2 features
pca = PCA(n_components = 2)
X_pca = pca.fit_transform(X)
X_pca.shape

(918, 2)

In [93]:
X_pca

array([[ 92.31150296, -29.44339488],
       [-17.14318296, -13.7477133 ],
       [ 81.9060306 ,  38.22291707],
       ...,
       [-69.00452422,  17.34009145],
       [ 39.20696975, -33.59377142],
       [-21.43603879, -37.22738029]])

In [94]:
pca.explained_variance_ratio_

array([0.92020198, 0.04913467])

In [95]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size = 0.2, random_state=30)

In [96]:
model = LogisticRegression()
model.fit(X_train_pca, y_train)
model.score(X_test_pca, y_test)

0.7010869565217391